---
- name: Install NGINX
  apt: 
    name: nginx 
    state: present 

# SSL

# - name: Create cert directory for the user
#   file:
#     path: "/home/{{ ansible_user }}/cert"
#     state: directory
#     mode: '0755'
#     owner: "{{ ansible_user }}"
#     group: "{{ ansible_user }}"

# - name: Generate a self-signed certificate for Nexus
#   shell: |
#     openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
#     -keyout /home/user-cloud/cert/nexus.key \
#     -out /home/user-cloud/cert/nexus.crt \
#     -subj "/C=MA/ST=RABAT/L=RABAT/O=DevOps360/OU=IT/CN=nexus.devops360.org"

- name: Add Nexus config for NGINX
  copy:
    src: ./../templates/nexus-nginx.conf
    dest: /etc/nginx/sites-available/nexus

- name: Enable site
  file:
    src: /etc/nginx/sites-available/nexus
    dest: /etc/nginx/sites-enabled/nexus
    state: link

- name: Remove default Nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Restart NGINX
  systemd:
    name: nginx 
    state: restarted