---
- name: Install NGINX
  apt: 
    name: nginx 
    state: present 

- name: Add Nexus config for NGINX
  copy:
    src: ./../templates/nexus-nginx.conf
    dest: /etc/nginx/sites-available/nexus

- name: Enable site
  file:
    src: /etc/nginx/sites-available/nexus
    dest: /etc/nginx/sites-enabled/nexus
    state: link

- name: Remove default Nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Restart NGINX
  systemd:
    name: nginx 
    state: restarted