---
- name: Install dependencies
  apt: 
    name: openjdk-11-jdk
    state: present 
    update_cache: yes

- name: Download and extract Nexus
  unarchive:
    src: https://download.sonatype.com/nexus/3/latest-unix.tar.gz
    dest: /opt
    remote_src: yes

- name: Create Nexus directory
  shell: mv /opt/nexus-3.* /opt/nexus

- name: Create Nexus user
  user: 
    name: nexus
    system: yes
    shell: /usr/sbin/nologin

- name: Set Ownership of Nexus directory
  file:
    path: /opt/nexus
    state: directory
    recurse: yes
    owner: nexus
    group: nexus
    mode: '0755'

- name: Set Ownership of SonaType directory
  file:
    path: /opt/sonatype-work
    state: directory
    recurse: yes
    owner: nexus
    group: nexus
    mode: '0755'


