apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "swiggy-frontend.fullname" . }}-green
  labels:
    app: {{ include "swiggy-frontend.fullname" . }}-green
spec:
  replicas: {{ .Values.greenImage.replicas }}
  selector:
    matchLabels:
      app: {{ include "swiggy-frontend.fullname" . }}-green
  template:
    metadata:
      labels:
        app: {{ include "swiggy-frontend.fullname" . }}-green
    spec:
      containers:
        - name: swiggy
          image: "{{ .Values.greenImage.repository }}:{{ .Values.greenImage.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.greenImage.pullPolicy }}
          ports:
            - containerPort: {{ .Values.greenImage.port }}