apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "swiggy-frontend.fullname" . }}-blue
  labels:
    app: {{ include "swiggy-frontend.fullname" . }}-blue
spec:
  replicas: {{ .Values.blue.replicas }}
  selector:
    matchLabels:
      app: {{ include "swiggy-frontend.fullname" . }}-blue
  template:
    metadata:
      labels:
        app: {{ include "swiggy-frontend.fullname" . }}-blue
    spec:
      containers:
        - name: app
          image: "{{ .Values.blue.repository }}:{{ .Values.blue.tag | default.Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.blue.pullPolicy }}
          ports:
            - containerPort: {{ .Values.blue.port }}

