{{- if .Values.blue.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "swiggy-frontend.fullname" . }}-blue
  labels:
    app: {{ include "swiggy-frontend.fullname" . }}
    version: blue
spec:
  replicas: {{ .Values.blue.replicas }}
  selector:
    matchLabels:
      app: {{ include "swiggy-frontend.fullname" . }}
      version: blue
  template:
    metadata:
      labels:
        app: {{ include "swiggy-frontend.fullname" . }}
        version: blue
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.blue.port }}
{{- end }}
