{{- if .Values.green.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "swiggy-frontend.fullname" . }}-green
  labels:
    app: {{ include "swiggy-frontend.fullname" . }}
    version: green
spec:
  replicas: {{ .Values.green.replicas }}
  selector:
    matchLabels:
      app: {{ include "swiggy-frontend.fullname" . }}
      version: green
  template:
    metadata:
      labels:
        app: {{ include "swiggy-frontend.fullname" . }}
        version: green
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.green.port }}
{{- end }}