{{- if .Values.createService }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "swiggy-frontend.fullname" . }}-service
  labels:
    app: {{ include "swiggy-frontend.fullname" . }}
spec:
  selector:
    app: {{ include "swiggy-frontend.fullname" . }}
    version: {{ .Values.service.targetDeployment }}
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      nodePort: {{ .Values.service.nodePort }}
{{- end }}