apiVersion: v1
kind: Service
metadata:
  name: {{ include "swiggy-frontend.fullname" . }}-service
  labels:
    app: {{ include "swiggy-frontend.fullname" . }}
spec:
  selector:
    app: {{ include "swiggy-frontend.fullname" . }}
    version: {{ .Values.current }}
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30010
