---
- hosts: dns
  user: user-cloud
  become: true
  roles:
    - DNS-Server

- hosts: runner
  user: user-cloud
  become: true
  roles:
    - Docker

- hosts: nexus
  user: user-cloud
  become: true
  roles:
    - Nexus

- hosts: sonar
  user: user-cloud
  become: true
  roles:
    - SonarQube

- hosts: gitlab
  user: user-cloud
  become: true
  roles:
    - Gitlab

- hosts: private
  user: user-cloud
  become: true
  roles:
    - DNS-Set




