---
- name: Install dependencies
  apt:
    name: 
      - curl
      - openssh-server
      - ca-certificates
    state: present
    update_cache: yes

- name: Add GitLab EE repository
  shell: curl -s https://packages.gitlab.com/install/repositories/gitlab/gitlab-ee/script.deb.sh | sudo bash

- name: Install GitLab EE
  apt:
    name: gitlab-ee
    state: present
  environment:
    EXTERNAL_URL: "http://gitlab.devops360.org" ## replace http to https for ssl